### PR TITLE
Configure prettier and eslint together

### PR DESCRIPTION
**Pull request by Jokauppi**
- Added eslint-plugin-prettier to disable conflicting rules from eslint
- Added prettier to lint scripts
- Fixed lint issues
- Enabled trailing commas
- change max line width to 80

### CODE REVIEW

**Comment by ArktinenKarpalo** [comment]
what is the reasoning behind apparently changing max line width from 120 to 80?

**Comment by Jokauppi** [comment]
> what is the reasoning behind apparently changing max line width from 120 to 80?

This is the Prettier default. Also in Prettier 2.0 some rules were changed causing many chained function calls to be formatted on one line. Setting line width to the default fixes most of these and forces them back on multiple lines. I'd argue this is more readable and closer to how the codebase looked before. Also shorter lines are nicer to work with on split screen editors.

**Comment by Jokauppi** [comment]
Conflicts between Prettier and Eslint are showing up constantly, merging this already. We can refine specific config details later.

**Comment by ArktinenKarpalo** [comment]
Some automated formatter seems like a very good idea. However I am _GREATLY_ disgusted by some of the formatting produced by "prettier". The heuristic used to split code into multiple lines seems inconsistent and the resulting code is difficult to read.

Few examples:

```diff
-const authMiddleware = (requiredRole = null, tokenSecret = process.env.JWT_SECRET) => {
+const authMiddleware = (
+    requiredRole = null,
+    tokenSecret = process.env.JWT_SECRET,
+) => {
```

```diff
-logger.error('Invalid authorization token (token contains nonexistent user or no roles)');
+logger.error(
+    'Invalid authorization token (token contains nonexistent user or no roles)',
+);
```

```diff
-const deleteUndefinedFields = require('../utils/objectUtils').deleteUndefinedFields;
+const deleteUndefinedFields =
+    require('../utils/objectUtils').deleteUndefinedFields;
```
```diff
knex('PERSONHIST')
-    .leftJoin('SALDOHISTORY', 'PERSONHIST.saldhistid', 'SALDOHISTORY.saldhistid')
+    .leftJoin(
+        'SALDOHISTORY',
+        'PERSONHIST.saldhistid',
+         'SALDOHISTORY.saldhistid',
+    )
    .leftJoin('RVPERSON', 'PERSONHIST.userid1', 'RVPERSON.userid')
    .leftJoin('ROLE', 'RVPERSON.roleid', 'ROLE.roleid')
```

I understand that some of these are opinion based and the objective of prettier is to decide on these things. But many formatting decisions that prettier does are just foolish. Forcing something like `a(b,c)` instead of `a (b,c)` (or the other way around) is useful. But in some parts of the code semantics should also be taken into account when formatting. This is especially the case with line width/multiline issues mentioned above. These things seem to be not configurable, developers of prettier have instead decided to force it all down your throat. I don't think that using prettier is worth it.

This pull request ruins git blame. A fix is to use --ignore-revs-file. Most if not all commits in this pull request should be squashed, so only 1 commit has to be included in the ignore file. (squashing commits is maybe something we should do more in general in all our pull requests, now that I think of it our commit history is horrendous)


Also now that we're on it, maybe we should change to tabs?

**Comment by Tuupertunut** [comment]
> what is the reasoning behind apparently changing max line width from 120 to 80?

It's not really max line width but the target line width for prettier, so it tries to split code into multiple lines until the lines are around 80 characters long. We tested different values for that and 80 seemed to be the most readable. Max line width in eslint is still 120 and there are some lines that are close to it.

IMO the prettier 1.x logic was better where it would always split into multiple lines when there were 3 or more arguments or method calls in a chain, but now that we use prettier 2.x it always tries to fill all lines to the target width, so target line width matters.

**Comment by ArktinenKarpalo** [comment]
> IMO the prettier 1.x logic was better where it would always split into multiple lines when there were 3 or more arguments or method calls in a chain, but now that we use prettier 2.x it always tries to fill all lines to the target width, so target line width matters.

Even that would make more sense than what it does currently. 

I'd like to hear arguments on why we should use prettier, what does it do that eslint does not? Split code into multiple lines in an attempt to enforce 80 char width limit seems to be the only thing, but it does this badly, so why use it?

**Comment by Jokauppi** [comment]
> This pull request ruins git blame. A fix is to use --ignore-revs-file. Most if not all commits in this pull request should be squashed, so only 1 commit has to be included in the ignore file.
 
Ignore-revs-file was new to me. Created a PR for the squash and the file here:
- #108

Could use some eyes on this in case I messed something up.

> Few examples

Apart from the require I think these are totally okay. The one line versions are impossible to read on split screen or a small laptop screen without horizontally scrolling.

> Some automated formatter seems like a very good idea. + I don't think that using prettier is worth it.

I'm open to any automated formatter and config, just important that there is one so we avoid needless changes and manual work. What would be best option here? It's clear that Eslint doesn't (want to) support formatting features anymore, see: 
- https://eslint.org/blog/2023/10/deprecating-formatting-rules/

- https://github.com/eslint/eslint/issues/17522

although community support is continuing through https://eslint.style/. The downside of going with just Eslint is that it doesn't format JSON, markdown or YAML like Prettier does. There seems to also be some newline rules that eslint is not able to enforce.

One standalone alternative would be [dprint](https://dprint.dev/overview/) mentioned in the Eslint blog. It seems to be more configurable than Prettier at least. Have to check how it handles chained calls / multiple arguments.

Edit: Created a  preview branch for dprint, some function rule defaults seem even worse than Prettier. These may be possible to configure but I couldn't find the appropriate options.  
- #109

Edit: Created a  preview branch for ESlint Stylistic, mostly works pretty well but doesn't support other languages besides JS/TS and has some small kinks.
- #110   

Whatever we choose it should support typescript in case we migrate and play ball will vscode as most of us are using it.

> squashing commits is maybe something we should do more in general in all our pull requests, now that I think of it our commit history is horrendous

Agreed. Should we consider only allowing squash merging in PRs?

> Also now that we're on it, maybe we should change to tabs?

Argeed. Missed that we were using spaces.

**Comment by ArktinenKarpalo** [comment]
>The downside of going with just Eslint is that it doesn't format JSON, markdown or YAML like Prettier does. 

Why would you want to have one library to format multitude of languages instead of separate one for each language? If we want to format json/yaml we should just use separate yaml/json formatters.

> I'm open to any automated formatter and config, just important that there is one so we avoid needless changes and manual work. What would be best option here? It's clear that Eslint doesn't (want to) support formatting features anymore.

I didn't know that eslint has deprecated their formatting. I will also look at what alternatives there are. The main issue with these alternatives has been that they don't seem to deal well with formatting code into multiple lines. (chaining functions etc.)

>Should we consider only allowing squash merging in PRs?

I'm not sure about that, sometimes there may be cases where having multiple commits makes the changes more readable. We're also in stage of project in which there could be major changes and stuff, compared to production code in which very small changes would probably be more common.

**Comment by Jokauppi** [comment]
Alright, probably prettier is fine to keep around for the other stuff?

The eslint deprecation is probably good on the whole so people spend less time solving conflicts with other formatters but yea sadly the choice in JS formatters is pretty limited. Would be nice if prettier was not so opinionated as it often seems to be the "industy standard".

**Comment by ArktinenKarpalo** [comment]
>Alright, probably prettier is fine to keep around for the other stuff?

I guess. Way less time is spent reading those files so it shouldn't matter too much how they're formatted.

>sadly the choice in JS formatters is pretty limited.

So it seems. I really don't understand why. With this ridiculous amount of line wrap its almost as if one was using ed to read the code, maybe javascript developers just turn their monitors sideways, who knows.

**Comment by ArktinenKarpalo** [comment]
If we go with prettier we should maybe consider https://biomejs.dev/ which supposedly is [prettier rewritten in rust](https://console.algora.io/challenges/prettier), being[ faster](https://github.com/biomejs/biome/blob/main/benchmark/README.md) and possibly[ fixing a few things](https://biomejs.dev/formatter/differences-with-prettier/).

Biome can also do linting but it seems to lack some rules that eslint has, haven't looked into it. 

From maintainability perspective, its Russian roulette. In 5 year these all options will be deprecated anyway and replaced with the newest hype. (its possible for this project to outlive them all, based on how long old rv service was in use)

**Comment by Jokauppi** [comment]
> With this ridiculous amount of line wrap its almost as if one was using ed to read the code, maybe javascript developers just turn their monitors sideways, who knows.

With everyone using VScode, some with sidebars on both sides, yea basically :D Probably that is why I'm usually satisfied with Prettier.

I stumbled across Biome as well, seemed promising. Future proofing is always a lottery especially with JS but maybe it makes for a fun rewrite project for someone to procrastinate with in the future :)

Edit: Most newer formatters seem to be built with ES6 modules in mind. Would be good to migrate to modules at some point as well.

**Comment by Jokauppi** [comment]
Created a branch to play around with Biome:
- #111

**Pull request merged**
