### PR TITLE
Eslint Stylistic formatting test

### PR DESCRIPTION
**Pull request by Jokauppi**
Here's a branch to preview and test ESlint Stylistic.

Seems to not be able to enforce some rules that prettier does but mostly works well.
- Doesn't lint JSON, YAML, or markdown
- Function parens/args cannot be configured to match the behavior of Prettier 1.x and mostly resembles Prettier 2.x
- Has weird problems with mixed spaces and tabs.

### CODE REVIEW

**Comment by ArktinenKarpalo** [comment]
This still seems to split all function chains to many lines, though multiline split can probably be disabled in eslint.
```diff
-    if (!(await knex.schema.hasTable('RVPERSON'))) {
-        await knex.schema.createTable('RVPERSON', (table) => {
-            table.increments('userid').primary();
-            table.dateTime('createdate').notNullable();
-            table
-                .integer('roleid')
-                .notNullable()
-                .references('roleid')
-                .inTable('ROLE');
-            table.string('name', 64).notNullable().index();
-            table.string('univident', 128).notNullable();
-            table.string('pass', 100).notNullable();
-            table.integer('saldo').notNullable();
-            table.string('realname', 128);
-            table.unique('name');
-            table.unique('univident');
-        });
-    }
+ 	if (!(await knex.schema.hasTable('RVPERSON'))) {
+		await knex.schema.createTable(
+			'RVPERSON',
+			(table) => {
+				table.increments('userid').primary();
+				table.dateTime('createdate').notNullable();
+				table
+					.integer('roleid')
+					.notNullable()
+					.references('roleid')
+					.inTable('ROLE');
+				table.string(
+					'name',
+					64,
+				).notNullable()
+					.index();
+				table.string(
+					'univident',
+					128,
+				).notNullable();
+				table.string(
+					'pass',
+					100,
+				).notNullable();
+				table.integer('saldo').notNullable();
+				table.string(
+					'realname',
+					128,
+				);
+				table.unique('name');
+				table.unique('univident');
+			},
+		);
+	}
```
The reason for formatting code is readability. In my opinion, this code is way less readable than the original.
Because we use a query builder we have a lot of chains like this in our code, formatting them manually makes the code more readable than what any automatic formatter (to date) can achieve. Yes you don't have to think about formatting if its completely automatic, but net gain in effort required is negative if the resulting code is hard to read and maintain.

**Comment by Jokauppi** [comment]
Yea this was not meant to be a final suggestion, you can experiment and make changes here.

The { "minItems": value } option from function-paren-newline would have been handy in  function-call-argument-newline but the best alternative would probably be "consistent" which is somewhere between automatic and manual.

Though it would be nice to not go too much over 80 line length, anything longer tends to roll off the screen and makes split git diffs much harder to review.

**Comment by ArktinenKarpalo** [comment]
Some parts of the code now contain so many newlines that the VERTICAL size in screen (which is more limited than horizontal) becomes an issue. One reads from left to right, not from top to bottom, so formatting code such that there are 10 lines with 1 word in each instead of 2 lines with 5 words is wasteful and slows down reading.

```js
module.exports.authenticateUser =
	(requiredRole = null, tokenSecret = process.env.JWT_SECRET) =>
		async (req, res) => {
			const body = req.body;
			const username = body.username;
			const password = body.password;

			const user = await userStore.findByUsername(username);
			if (user) {
				if (
					password != undefined &&
					(await userStore.verifyPassword(password, user.passwordHash))
				) {
					if (verifyRole(requiredRole, user.role)) {
						logger.info(
							'User %s logged in as role %s',
							user.username,
							requiredRole,
						);
						res.status(200).json({
							accessToken: token.sign(
								{userId: user.userId},
								tokenSecret,
							),
						});
					} else {
						logger.error(
							'User %s is not authorized to login as role %s',
							user.username,
							requiredRole,
						);
						res.status(403).json({
							error_code: 'not_authorized',
							message: 'Not authorized',
						});
					}
				} else {
					logger.error(
						'Failed to login with username and password. Username was %s',
						username,
					);
					res.status(401).json({
						error_code: 'invalid_credentials',
						message: 'Invalid username or password',
					});
				}
			} else {
				logger.error(
					'Failed to login with username and password. Username was %s',
					username,
				);
				res.status(401).json({
					error_code: 'invalid_credentials',
					message: 'Invalid username or password',
				});
			}
	
```
This is not even (only) about width limit of 80, but the fact that these formatters simply cannot format multiline code in a sensible way. There is more in this issue than width of lines.

Wasting a whole line (even if limited to only 80 chars) for only this is not good!
```
if (
```

**Comment by Jokauppi** [comment]
Closing as we chose Biome

**Pull request closed without merging**
